[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/vimproc.vim'
build = 'make'

[[plugins]]
repo = 'Shougo/unite.vim.git'
hook_add = 'source ~/.dotfiles/vimrc/plugins/unite.vim'

[[plugins]]
repo = 'thinca/vim-quickrun'
hook_add = 'source ~/.dotfiles/vimrc/plugins/quickrun.vim'

[[plugins]]
repo = 'tomtom/tcomment_vim'

[[plugins]]
depends = ['unite']
repo = 'Shougo/neomru.vim'

[[plugins]]
repo = 'w0ng/vim-hybrid'
hook_add = 'source ~/.dotfiles/vimrc/plugins/colorscheme.vim'

[[plugins]]
repo = 'Yggdroot/indentLine'
hook_add = 'source ~/.dotfiles/vimrc/plugins/indentline.vim'

[[plugins]]
repo = 'scrooloose/syntastic'
hook_add = 'source ~/.dotfiles/vimrc/plugins/syntastic.vim'

[[plugins]]
repo = 'tpope/vim-fugitive' 
hook_add = 'source ~/.dotfiles/vimrc/plugins/fugitive.vim' 

[[plugins]]
repo = 'itchyny/lightline.vim'
hook_add = 'source ~/.dotfiles/vimrc/plugins/lightline.vim'

[[plugins]]
repo = 'jiangmiao/auto-pairs'
