[[plugins]]
repo = 'tell-k/vim-autopep8'
hook_add = 'source ~/.dotfiles/vimrc/plugins/autopep8.vim'
on_ft = ['python']

[[plugins]]
repo = 'joonty/vdebug'
on_ft = ['python']
 
[[plugins]]
repo = 'kh3phr3n/python-syntax'
hook_add = 'source ~/.dotfiles/vimrc/plugins/python-syntax.vim'
on_ft = ['python']












[[plugins]]
repo = 'Shougo/neocomplete'
hook_add = 'source ~/.dotfiles/vimrc/plugins/neocomplete.vim'
on_if = 0

[[plugins]]
repo = 'Shougo/neosnippet'
depends = ['neocomplete']
on_if = 0

[[plugins]]
repo = 'Shougo/neosnippet-snippets'
depends = ['neosnippet']
on_if = 0

[[plugins]]
repo = 'davidhalter/jedi-vim'
hook_add = 'source ~/.dotfiles/vimrc/plugins/jedi.vim'
on_if = 0

